### ISSUE TITLE
Composer package

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto-package-generator#1]
It would be better if we add a composer file and register the package at [packagist](https://packagist.org).

### Todo:

- [x] Create a json file
- [x] Use package discovery https://laravel.com/docs/7.x/packages#package-discovery
- [x] Register the package on packagist.

**Comment by jitendra-webkul** [comment]
Package in registered in packagist

https://packagist.org/packages/bagisto/bagisto-package-generator
